export const HOME_CHANGE_SECRETS_LIST_PATH = 'HOME_CHANGE_SECRETS_LIST_PATH';
export const HOME_CHANGE_SECRETS_LIST_FILTER = 'HOME_CHANGE_SECRETS_LIST_FILTER';
export const HOME_CHANGE_SELECTED_SECRET = 'HOME_CHANGE_SELECTED_SECRET';
